DATALOADER:
  TRAIN_S:
    SAMPLER: 'RandomDomainSampler'
    BATCH_SIZE: 256
  TRAIN_T:
    SAME_AS_S: False
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 256

OPTIM:
  NAME: 'sgd'
  LR: 0.01
  STEPSIZE: [50]
  MAX_EPOCH: 50
  LR_SCHEDULER: 'cosine'


TRAINER:
  MSDTR:
    HIDDEN: [1024,512]
    DIS_SIZE: 778
    RECONSTRUCTION: 1
    cls_d: 0.1
    adv_begin: 0
    mask_b: 0.6
    mask_k: 3
    g: 0.1
