DATALOADER:
  NUM_WORKERS: 4
  TRAIN_S:
    SAMPLER: 'RandomDomainSampler'
    BATCH_SIZE: 72
  TRAIN_T:
    SAME_AS_S: False
    BATCH_SIZE: 24
  TEST:
    BATCH_SIZE: 96

OPTIM:
  NAME: 'sgd'
  LR: 0.001
  MAX_EPOCH: 50
  LR_SCHEDULER: 'cosine'

TRAIN:
  COUNT_ITER: 'bigger_one'

TRAINER:
  MSDTR:
    HIDDEN: [1024, 778]
    DIS_SIZE: 1024
    RECONSTRUCTION: 6
    cls_d: 0.2
    adv_begin: 0
    mask_b: 0.4
    mask_k: 2
    g: 0.001
    lr_muti_g: 0.0
    lr_muti_ddi: 0.0
    lr_muti_cdi: 0.0
    lr_muti_dds: 0.0
    lr_muti_cds: 0.0
    lr_muti_r: 10.0
    lr_muti_dis: 10.0



